GET http://localhost:5028/games

###

GET http://localhost:5028/games/1

###
Post http://localhost:5028/games
content-Type: application/json

{
    "name": "Galactic Wars",
    "genre": "Sci-Fi",
    "price": 44.99,
    "releaseDate": "2025-06-15"
}

###
Put http://localhost:5028/games/1
Content-Type: application/json

{
  "name": "Cyberpunk 2077: Phantom Liberty",
  "genre": "RPG",
  "price": 29.99,
  "releaseDate": "2023-09-26"
}

###
Delete http://localhost:5028/games/1
